project:
  output-dir: _pdf_build

book:
  output-file: "lagrange-finance"
format:
  pdf:
    pdf-engine: lualatex
    documentclass: ltjsbook
    papersize: a4
    toc: true
    number-sections: false
    keep-tex: true

    classoption:
      - openany

    include-in-header:
      text: |
        \usepackage[haranoaji]{luatexja-preset}
        \usepackage{graphicx}
        \usepackage{eso-pic}
        \usepackage{fvextra}

        % Cover
        \renewcommand{\maketitle}{%
          \thispagestyle{empty}
          \AddToShipoutPictureBG*{%
            \AtPageLowerLeft{%
              \includegraphics[width=\paperwidth,height=\paperheight]{images/cover.png}%
            }%
          }%
          \null
          \clearpage
        }

        % Code blocks
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
          commandchars=\\\{\},
          fontsize=\scriptsize,
          breaklines=true,
          breakanywhere=true
        }

    geometry:
      - top=18mm
      - bottom=18mm
      - left=18mm
      - right=18mm