project:
  output-dir: _pdf_build

book:
  title: "ラグランジェ・ファイナンス"
  subtitle: "Quant Technology 1st Step"
  author: "Eiichi Horigome"
  output-file: "lagrange-finance"

  chapters:
    - part1_empirical/ch01_r_basics_tidyverse.qmd
    - part1_empirical/ch02_financial_data.qmd
    - part1_empirical/ch03_stock_data_time_series.qmd
    - part1_empirical/ch04_factor_models.qmd
    - part1_empirical/ch05_asset_pricing.qmd
    - part1_empirical/ch06_event_study.qmd

    - part2_quantive_riemann/ch01_deterministic_cashflow_valuation.qmd
    - part2_quantive_riemann/ch02_interest_rate_curves.qmd
    - part2_quantive_riemann/ch03_ois_swaps_multicurve.qmd
    - part2_quantive_riemann/ch04_black_model.qmd
    - part2_quantive_riemann/ch05_normal_model.qmd
    - part2_quantive_riemann/ch06_sabr_model.qmd
    - part2_quantive_riemann/ch07_callable_hull_white.qmd
    - part2_quantive_riemann/ch08_credit_risk_cds.qmd
    - part2_quantive_riemann/ch09_exotic_derivatives_prdc.qmd