project:
  type: book
  execute-dir: project
book:
  title: "ラグランジェ・ファイナンス"
  subtitle: "First Step in Quant Technology"
  author: "Eiichi Horigome"

  chapters:
    - index.qmd

    - part: "第I部 実証会計・ファイナンス"
      chapters:
        - part1_empirical/ch01_r_basics_tidyverse.qmd
        - part1_empirical/ch02_financial_data.qmd
        - part1_empirical/ch03_stock_data_time_series.qmd
        - part1_empirical/ch04_factor_models.qmd
        - part1_empirical/ch05_asset_pricing.qmd
        - part1_empirical/ch06_event_study.qmd

    - part: "第II部 金融工学と金融数学"
      chapters:
        - part2_quantive_riemann/ch01_deterministic_cashflow_valuation.qmd
        - part2_quantive_riemann/ch02_interest_rate_curves.qmd
        - part2_quantive_riemann/ch03_ois_swaps_multicurve.qmd
        - part2_quantive_riemann/ch04_black_model.qmd
        - part2_quantive_riemann/ch05_normal_model.qmd
        - part2_quantive_riemann/ch06_sabr_model.qmd
        - part2_quantive_riemann/ch07_callable_hull_white.qmd
        - part2_quantive_riemann/ch08_credit_risk_cds.qmd
        - part2_quantive_riemann/ch09_exotic_derivatives_prdc.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: false
    number-sections: false

execute:
  eval: false
  echo: true
  warning: false
  message: false
  error: true
