# Chapter 05


## ch05_01


```{r}
#| message: false
#| warning: false
# ch05_01: tidyverseと株式データの読み込み

library(tidyverse)
stock_data <- read_csv("ch05_stock_data.csv")
```

## ch05_02


```{r}
#| message: false
#| warning: false
# ch05_02: 株式データの目視

print(stock_data)
```

## ch05_03


```{r}
#| message: false
#| warning: false
# ch05_03: 配当支払いや発行済株式数変化の例

stock_data %>% 
  filter(firm_ID == 1 & month_ID %in% 27:30)
```

## ch05_04


```{r}
#| message: false
#| warning: false
# ch05_04: 調整係数が1以外の値を取る例

stock_data %>% 
  filter(firm_ID == 74 & month_ID %in% 29:32)
```

## ch05_05


```{r}
#| message: false
#| warning: false
# ch05_05: 時価総額の追加

stock_data <- stock_data %>% 
  mutate(ME = stock_price * shares_outstanding)
```

## ch05_06


```{r}
#| message: false
#| warning: false
# ch05_06: 時価総額の分布をヒストグラムで可視化

library(scales)

ggplot(stock_data) +
  geom_histogram(aes(x = ME)) +
  labs(x = "Market Equity", y = "Count") + 
  scale_x_continuous(limits = c(0, quantile(stock_data$ME, 0.95)), # x軸の上限を95%点に設定
                     labels = label_comma(scale = 1e-6)) + # 単位を100万円にした上で桁区切りのカンマを追加
  scale_y_continuous(expand = c(0, 0)) + 
  theme_classic()
```

## ch05_07


```{r}
#| message: false
#| warning: false
# ch05_07: 前月の株価を追加

stock_data %>% 
  group_by(firm_ID) %>% # firm_IDに関してグループ化
  mutate(lagged_stock_price = lag(stock_price)) %>% 
  ungroup()
```

## ch05_08


```{r}
#| message: false
#| warning: false
# ch05_08: 月次リターンの追加

stock_data <- stock_data %>% 
  group_by(firm_ID) %>% 
  mutate(lagged_stock_price = lag(stock_price)) %>% 
  ungroup() %>% 
  mutate(R = ((stock_price + DPS) * adjustment_coefficient - lagged_stock_price) / lagged_stock_price) # (5.1)式に従って月次リターンを計算
```

## ch05_09


```{r}
#| message: false
#| warning: false
# ch05_09: 月次超過リターンの追加

stock_data <- stock_data %>%
  mutate(Re = R - R_F) # 月次超過リターンを計算
```

## ch05_10


```{r}
#| message: false
#| warning: false
# ch05_10: 月次リターンの要約統計量を確認

summary(stock_data$R)

##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
## -0.3803 -0.0406  0.0103  0.0159  0.0648  0.5150    1515 
```

## ch05_11


```{r}
#| message: false
#| warning: false
# ch05_11: 月次リターンの標準偏差と分散を計算

sd(stock_data$R, na.rm = TRUE) # na.rm = TRUEを忘れると計算結果はNAに
## [1] 0.09113098

var(stock_data$R, na.rm = TRUE)
## [1] 0.008304855
```

## ch05_12


```{r}
#| message: false
#| warning: false
# ch05_12: 月次リターンの歪度を計算

skewness <- function(x) (1 / length(x)) * sum(((x - mean(x)) / sd(x))^3) # 歪度を計算する関数の定義

skewness(na.omit(stock_data$R)) # 欠損値を削除した上で代入

## [1] 0.5065672
```

## ch05_13


```{r}
#| message: false
#| warning: false
# ch05_13: 月次リターンの尖度を計算

kurtosis <- function(x) (1 / length(x)) * sum(((x - mean(x)) / sd(x))^4) # 尖度を計算する関数の定義

kurtosis(na.omit(stock_data$R)) # 欠損値を削除した上で代入

## [1] 4.268045
```

## ch05_14


```{r}
#| message: false
#| warning: false
# ch05_14: 月次リターンの分布をヒストグラムで可視化

ggplot(stock_data) + 
  geom_histogram(aes(x = R)) + 
  labs(x = "Monthly Stock Return", y = "Count") + 
  scale_y_continuous(expand = c(0, 0)) +
  theme_classic()
```

## ch05_15


```{r}
#| message: false
#| warning: false
# ch05_15: 月次リターンを累積して年次リターンを計算 (1)

annual_stock_data <- stock_data %>% 
  group_by(firm_ID, year) %>% # firm_IDとyearのペアでグループ化
  summarize(R = prod(1 + R) - 1, # バイ・アンド・ホールドの年次リターン
            R_F = prod(1 + R_F) - 1) %>%
  mutate(Re = R - R_F) %>%
  select(firm_ID, year, R, Re, R_F) %>%
  ungroup()
```

## ch05_16


```{r}
#| message: false
#| warning: false
# ch05_16: 月次リターンを累積して年次リターンを計算 (2)

stock_data %>% 
  group_by(firm_ID, year) %>% 
  summarize(simple_cumulative_R = sum(R)) %>% # 元本が一定となるよう毎月リバランスした場合の年次リターン
  ungroup()
```

## ch05_17


```{r}
#| message: false
#| warning: false
# ch05_17: 財務データと株式データの行数を確認

financial_data <- read_csv("ch04_output.csv")

nrow(financial_data) # 年次財務データの行数
## [1] 7919

nrow(annual_stock_data) # 年次リターン・データの行数
## [1] 7920

nrow(stock_data) # 月次リターン・データの行数
## [1] 95040
```

## ch05_18


```{r}
#| message: false
#| warning: false
# ch05_18: 年次リターン・データと財務データの結合 (1)

annual_data <- annual_stock_data %>%
  full_join(financial_data, by = c("firm_ID", "year")) # firm_IDとyearのペアをキーとして設定
```

## ch05_19


```{r}
#| message: false
#| warning: false
# ch05_19: 年次リターン・データと財務データの結合 (2)

annual_data <- annual_stock_data %>% 
  full_join(financial_data) # キーを省略した場合, 列名が同じ変数がキーに

## Joining, by = c("firm_ID", "year")
```

## ch05_20


```{r}
#| message: false
#| warning: false
# ch05_20: 月次リターン・データと財務データの結合

monthly_data  <- stock_data %>%
  full_join(financial_data, by = c("firm_ID", "year"))
```

## ch05_21


```{r}
#| message: false
#| warning: false
# ch05_21: full_join()関数による欠損値の処理

A <- tibble(firm_ID = c(1, 2), stock_price = c(120, 500)) # データセットの作成
B <- tibble(firm_ID = c(1, 3), DPS = c(5, 10))

full_join(A, B, by = "firm_ID") # A %>% full_join(B, by = "firm_ID")と書いても同じ
```

## ch05_22


```{r}
#| message: false
#| warning: false
# ch05_22: inner_join()関数による欠損値の処理

inner_join(A, B, by = "firm_ID")
```

## ch05_23


```{r}
#| message: false
#| warning: false
# ch05_23: left_join()関数，及びright_join()関数による欠損値の処理

left_join(A, B, by = "firm_ID")
right_join(A, B, by = "firm_ID")
```

## ch05_24


```{r}
#| message: false
#| warning: false
# ch05_24: 年度末の時価総額を年次データに追加

annual_data <- stock_data %>% 
  filter(month == 12) %>% # 12月のデータのみを抽出
  select(year, firm_ID, ME) %>% # 追加したい列のみ選択
  full_join(annual_data, ., by = c("year", "firm_ID")) %>% # 年次データと結合
  mutate(ME = ME / 1e6) # 時価総額の単位を百万円に
```

## ch05_25


```{r}
#| message: false
#| warning: false
# ch05_25: 売上高・当期純利益・時価総額をバブルチャートで可視化

annual_data %>% 
  filter(year == 2015,
         firm_ID %in% 2:20, # firm_IDが2から20のデータを抽出
         X > 0) %>% # 対数を取るため当期純利益（X）が正のデータのみ抽出
  ggplot() + 
  geom_point(aes(x = log(sales), y = log(X), size = ME), alpha = 0.4) + # バブルチャートを描くにはsize引数を指定
  scale_size(range = c(1, 20), name = "Market Equity") + # range引数でバブルの最小・最大面積を指定
  scale_x_continuous(limits = c(8, 14)) + # 両軸の範囲を指定
  scale_y_continuous(limits = c(2, 11)) +
  theme_classic()
```

## ch05_26


```{r}
#| message: false
#| warning: false
# ch05_26: firm_IDが1の企業の月次超過リターンを折れ線グラフで可視化

stock_data %>%
  filter(firm_ID == 1) %>% # firm_IDが1の企業のデータのみ抽出
  ggplot() + 
  geom_line(aes(x = month_ID, y = Re)) + # x軸にmonth_ID, y軸に月次超過リターンを表示
  labs(x = "Month ID", y = "Firm 1's Monthly Excess Return") + 
  scale_x_continuous(expand = c(0.01, 0)) + # 折れ線グラフとy軸の間の空白を指定
  theme_classic()
```

## ch05_27


```{r}
#| message: false
#| warning: false
# ch05_27: firm_IDが1の企業の月次超過リターンをヒストグラムで可視化

stock_data %>%
  filter(firm_ID == 1) %>% 
  ggplot() + 
  geom_histogram(aes(x = Re)) + 
  labs(x = "Firm 1's Monthly Excess Return", y = "Count") +
  scale_y_continuous(expand = c(0, 0)) + 
  theme_classic()
```

## ch05_28


```{r}
#| message: false
#| warning: false
# ch05_28: firm_IDが1の企業の平均月次超過リターンを計算

stock_data %>% 
  filter(firm_ID == 1) %>% 
  select(Re) %>%
  unlist() %>% # データフレームからベクトルに変換
  mean(na.rm = TRUE) # 第一引数は月次超過リターンのベクトル

## [1] 0.02906058
```

## ch05_29


```{r}
#| message: false
#| warning: false
# ch05_29: 月次超過リターンの期待値に関するt検定 (1)

Re_firm_ID_1 <- stock_data %>%
  filter(firm_ID == 1) %>% # firm_IDが1の企業のみ抽出
  select(Re) %>% # 月次超過リターンのみ抽出
  drop_na() %>% # 欠損値を削除
  unlist() # データフレームからベクトルに変換

mu0 <- 0 # 帰無仮説を期待値0と設定
n <- length(Re_firm_ID_1) # 標本サイズ

t_value <- (mean(Re_firm_ID_1) - mu0) / sqrt(var(Re_firm_ID_1) / n) # 定義に従ってt値を計算

## [1] 2.121296
```

## ch05_30


```{r}
#| message: false
#| warning: false
# ch05_30: 月次超過リターンの期待値に関するt検定 (2)

t.test(Re_firm_ID_1) # t.test()関数で第二引数以降を省略
```

## ch05_31


```{r}
#| message: false
#| warning: false
# ch05_31: 簿価時価比率と株式リターンの関係を可視化

lm_sample_data <- annual_data %>% 
  group_by(firm_ID) %>%
  mutate(lagged_BEME = lagged_BE / lag(ME)) %>% # 企業ごとに前年度の簿価時価比率を計算
  ungroup() %>%
  filter(year == 2016, # firm_IDが1から10までの企業の2016年のデータを抽出
         firm_ID <= 10) %>%
  select(firm_ID, year, Re, lagged_BEME) %>% # 必要な列のみ抽出
  drop_na() # 欠損データを削除 

ggplot(lm_sample_data) + 
  geom_point(aes(x = lagged_BEME, y = Re)) + # x軸に簿価時価比率, y軸に超過リターン
  labs(x = "BE/ME at the End of Year t", y = "Excess Return for Year t + 1") + 
  theme_classic()
```

## ch05_32


```{r}
#| message: false
#| warning: false
# ch05_32: 簿価時価比率と株式リターンの散布図に回帰直線を追加

ggplot(lm_sample_data) + 
  geom_point(aes(x = lagged_BEME, y = Re)) + 
  geom_smooth(aes(x = lagged_BEME, y = Re), method = "lm", se = FALSE, color = "black") + # 回帰直線を追加するにはgeom_smooth()関数を用いる
  labs(x = "BE/ME at the End of Year t", y = "Excess Return for Year t + 1") + 
  theme_classic()
```

## ch05_33


```{r}
#| message: false
#| warning: false
# ch05_33: lm()関数を用いた線形回帰

lm_results <- lm(Re ~ lagged_BEME, data = lm_sample_data) # ~の左に従属変数, 右に独立変数を記す
names(lm_results)

## [1] "coefficients"  "residuals"     "effects"       "rank"       "fitted.values" "assign"        "qr"            "df.residual"       "xlevels"       "call"          "terms"         "model"  
```

## ch05_34


```{r}
#| message: false
#| warning: false
# ch05_34: lm()関数で計算した回帰係数

print(lm_results$coefficients)

## (Intercept) lagged_BEME 
## 0.05513385  0.07552921 
```

## ch05_35


```{r}
#| message: false
#| warning: false
# ch05_35: broomパッケージのtidy()関数で係数の推定値に関する結果を確認

install.packages("broom")
library(broom)

tidy(lm_results)
```

## ch05_36


```{r}
#| message: false
#| warning: false
# ch05_36: broomパッケージのglance()関数でモデル全体の当てはまりを確認

glance(lm_results)
```

## ch05_37


```{r}
#| message: false
#| warning: false
# ch05_37: 線形・対数モデルによる推定

tidy(lm(Re ~ log(lagged_BEME), data = lm_sample_data)) # 右辺のみlog()関数で自然対数を取る
```

## ch05_38


```{r}
#| message: false
#| warning: false
# ch05_38: データの保存

write_csv(monthly_data, "ch05_output1.csv")
write_csv(annual_data, "ch05_output2.csv")
```
